### ISSUE TITLE
kibana.yml created by cookbook is ignored

### ISSUE THREAD

**Issue by rhass-r7** [rchukh/chamber-kibana#28]
Kibana 4.0.0 reads the config file `/usr/local/kibana/conf/kibana.yml` opposed the file dropped by the cookbook `/usr/local/etc/kibana/kibana.yml`

**Comment by rchukh** [comment]
The need for integration tests (#21) just got bigger...

Apparently, there is no way to reload startup parameters in [kibana.sh](https://github.com/elasticsearch/kibana/blob/master/src/server/bin/kibana.sh)...
And I don't want to do it with `line` cookbook, because the `kibana.sh` format changed between BETA 1 and BETA 3.

For now we need to add our own `kibana.sh` that will be used instead of original one, until Kibana itself would allow the parameters override. (looking that it is already done for elasticsearch, they will probably implement it in kibana sooner or later)

**Comment by rchukh** [comment]
I am going to look into it tomorrow, and hopefully release a 0.2.1 also.

**Comment by rhass-r7** [comment]
I started looking into fixing the issue this morning, I have been stumbling on the chefspec -- for whatever reason I cannot get rspec to against your cookbook using the current chef-dk as my environment. One of the issues was the inclusion Fuubar which is incompatible with the current version of rspec, and also possibly the use of .ruby-version... however I haven't been able to get past the stack trace.

See if this spec runs for you... I this should at cause the last example to fail. I didn't add the logic to test for a symlink or fix the symlink in the recipe yet, but primarily because I didn't have a way to test it via chefspec. 

``` diff
--- a/spec/unit/recipes/default_spec.rb
+++ b/spec/unit/recipes/default_spec.rb
@@ -19,6 +19,7 @@ describe 'chamber-kibana::default' do
     runner.node.set['kibana']['checksum'] = '0010e467d598b67ba442c2edc5c6df196e8734f826044a58e0da3490a1bb587a'
     runner.node.set['kibana']['host'] = 'http://download.elasticsearch.org'
     runner.node.set['kibana']['repository'] = 'kibana/kibana'
+    runner.node.set['kibana']['elasticsearch']['server'] = 'http://foobar.com:9200'
     runner.converge(described_recipe)
   end

@@ -116,5 +117,11 @@ describe 'chamber-kibana::default' do
       mode: 00755
     }
     expect(chef_run).to create_template('kibana.yml').with(attributes)
+    expect(chef_run).to render_file(
+      ::File.join(chef_run.node['kibana']['path']['conf'], 'kibana.yml').with_content(
+        /^elasticsearch: "http:\/\/foobar.com:9200"$/
+      )
+    )
   end
+
 end
```

**Comment by rchukh** [comment]
Thanks.

I am not very familiar with Chef-DK specifics, but could you please mention how you run the `rspec` tests? With `bundle exec`, `rake` task, or directly?

**Comment by rchukh** [comment]
Released in https://supermarket.chef.io/cookbooks/chamber-kibana/versions/0.2.1

I will add additional tests in scope of **integration-tests** branch and the #21 issue.
